//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aeroflot_from_hell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int kod { get; set; }
        public string login1 { get; set; }
        public string password { get; set; }
        public string rights { get; set; }
    }
}
