//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aeroflot_from_hell
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AeroflotEntities : DbContext
    {
        public AeroflotEntities()
            : base("name=AeroflotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flight_detail> Flight_details { get; set; }
        public virtual DbSet<Login> Logins { get; set; }

        private static AeroflotEntities context;

        public static AeroflotEntities GetContext()
        {
            if (context == null)
                context = new AeroflotEntities();
            return context;
        }
    }
}
